name = "lumi-core-api"
main = "src/index.ts"
compatibility_date = "2025-12-28"

# ルートが api.luminabulige.com に紐づいてる前提
routes = [
  { pattern = "api.luminabulige.com/*", zone_name = "luminabulige.com" }
]

[env.production]
# Production environment inherits from base config
