name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  detect_breaking_changes:
    runs-on: 'ubuntu-latest'
    name: detect-breaking-changes
    if: github.repository == 'lumina-bulige-dev/lumi-os'
    steps:
      - name: Calculate fetch-depth
        run: |
          COMMITS="${{ github.event.pull_request.commits }}"
          if [ -z "$COMMITS" ] || ! [ "$COMMITS" -eq "$COMMITS" ] 2>/dev/null; then
            echo "FETCH_DEPTH=50" >> $GITHUB_ENV
          else
            echo "FETCH_DEPTH=$(expr $COMMITS + 1)" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4
        with:
          # Ensure we can check out the pull request base in the script below.
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install

      - name: Detect breaking changes
        run: |
          # Try to check out previous versions of the breaking change detection script. This ensures that
          # we still detect breaking changes when entire files and their tests are removed.
          git checkout "${{ github.event.pull_request.base.sha }}" -- ./scripts/detect-breaking-changes 2>/dev/null || true
          ./scripts/detect-breaking-changes ${{ github.event.pull_request.base.sha }}
